In [1]:
import pandas as pd
Raw_housing= pd.read_csv("/content/drive/My Drive/MLInternshaala/Transformed_Housing_Data2(1).csv")

In [2]:
Raw_housing.head(5)

   Sale_Price  ...  Zipcode_Group_Zipcode_Group_9
0    221900.0  ...                              0
1    538000.0  ...                              0
2    180000.0  ...                              0
3    604000.0  ...                              0
4    510000.0  ...                              0

[5 rows x 31 columns]

In [3]:
 Y =Raw_housing.iloc[:,0]
 X=Raw_housing.iloc[:,1:31]

In [4]:
X.head(5)

   No of Bedrooms  ...  Zipcode_Group_Zipcode_Group_9
0               3  ...                              0
1               3  ...                              0
2               2  ...                              0
3               4  ...                              0
4               3  ...                              0

[5 rows x 30 columns]

In [5]:
Y.head(5)

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: Sale_Price, dtype: float64

In [7]:
Raw_housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21609 entries, 0 to 21608
Data columns (total 31 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Sale_Price                                 21609 non-null  float64
 1   No of Bedrooms                             21609 non-null  int64
 2   No of Bathrooms                            21609 non-null  float64
 3   Flat Area (in Sqft)                        21609 non-null  float64
 4   Lot Area (in Sqft)                         21609 non-null  float64
 5   No of Floors                               21609 non-null  float64
 6   No of Times Visited                        21609 non-null  int64
 7   Overall Grade                              21609 non-null  int64
 8   Area of the House from Basement (in Sqft)  21609 non-null  float64
 9   Basement Area (in Sqft)                    21609 non-null  int64
 10  Age of House (in Years)                    21609 non-null  int64
 11  Latitude                                   21609 non-null  float64
 12  Longitude                                  21609 non-null  float64
 13  Living Area after Renovation (in Sqft)     21609 non-null  float64
 14  Lot Area after Renovation (in Sqft)        21609 non-null  int64
 15  Years Since Renovation                     21609 non-null  int64
 16  Condition_of_the_House_Excellent           21609 non-null  int64
 17  Condition_of_the_House_Fair                21609 non-null  int64
 18  Condition_of_the_House_Good                21609 non-null  int64
 19  Condition_of_the_House_Okay                21609 non-null  int64
 20  Ever_Renovated_Yes                         21609 non-null  int64
 21  Waterfront_View_Yes                        21609 non-null  int64
 22  Zipcode_Group_Zipcode_Group_1              21609 non-null  int64
 23  Zipcode_Group_Zipcode_Group_2              21609 non-null  int64
 24  Zipcode_Group_Zipcode_Group_3              21609 non-null  int64
 25  Zipcode_Group_Zipcode_Group_4              21609 non-null  int64
 26  Zipcode_Group_Zipcode_Group_5              21609 non-null  int64
 27  Zipcode_Group_Zipcode_Group_6              21609 non-null  int64
 28  Zipcode_Group_Zipcode_Group_7              21609 non-null  int64
 29  Zipcode_Group_Zipcode_Group_8              21609 non-null  int64
 30  Zipcode_Group_Zipcode_Group_9              21609 non-null  int64
dtypes: float64(9), int64(22)
memory usage: 5.1 MB

In [8]:
X.describe()

       No of Bedrooms  ...  Zipcode_Group_Zipcode_Group_9
count    21609.000000  ...                   21609.000000
mean         3.370771  ...                       0.002314
std          0.929916  ...                       0.048048
min          0.000000  ...                       0.000000
25%          3.000000  ...                       0.000000
50%          3.000000  ...                       0.000000
75%          4.000000  ...                       0.000000
max         33.000000  ...                       1.000000

[8 rows x 30 columns]