In [7]:
import pandas as pd
data=pd.read_csv("/content/drive/My Drive/MLInternshaala/NaN_Housing_Prices.csv")

In [2]:
data.head()

   Sale_Price  ...  Zipcode_Group_Zipcode_Group_9
0    221900.0  ...                              0
1    538000.0  ...                              0
2    180000.0  ...                              0
3    604000.0  ...                              0
4    510000.0  ...                              0

[5 rows x 31 columns]

In [3]:
data.head().shape

(5, 31)

In [4]:
data.isnull().sum()

Sale_Price                                       0
No of Bedrooms                                   0
No of Bathrooms                                  0
Flat Area (in Sqft)                              0
Lot Area (in Sqft)                               0
No of Floors                                     0
No of Times Visited                          19485
Overall Grade                                    0
Area of the House from Basement (in Sqft)        0
Basement Area (in Sqft)                      13123
Age of House (in Years)                          0
Latitude                                         0
Longitude                                        0
Living Area after Renovation (in Sqft)           0
Lot Area after Renovation (in Sqft)              0
Years Since Renovation                       20695
Condition_of_the_House_Excellent                 0
Condition_of_the_House_Fair                      0
Condition_of_the_House_Good                      0
Condition_of_the_House_Okay                      0
Ever_Renovated_Yes                               0
Waterfront_View_Yes                              0
Zipcode_Group_Zipcode_Group_1                    0
Zipcode_Group_Zipcode_Group_2                    0
Zipcode_Group_Zipcode_Group_3                    0
Zipcode_Group_Zipcode_Group_4                    0
Zipcode_Group_Zipcode_Group_5                    0
Zipcode_Group_Zipcode_Group_6                    0
Zipcode_Group_Zipcode_Group_7                    0
Zipcode_Group_Zipcode_Group_8                    0
Zipcode_Group_Zipcode_Group_9                    0
dtype: int64

In [5]:
for i in data.columns:
  tmp=data[i].isnull().sum()/len(data)
  if tmp > 0.70:
    print("removeing column:"+i+"with missing value ratio",tmp)
    data=data.drop(columns=[i])

removeing column:No of Times Visitedwith missing value ratio 0.9017076218242399
removeing column:Years Since Renovationwith missing value ratio 0.9577028090147623

In [9]:
data=pd.read_csv("/content/drive/My Drive/MLInternshaala/Raw_Housing_Prices3.csv")
data.head()

           ID  ... Lot Area after Renovation (in Sqft)
0  7129300520  ...                                5650
1  6414100192  ...                                7639
2  5631500400  ...                                8062
3  2487200875  ...                                5000
4  1954400510  ...                                7503

[5 rows x 21 columns]

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21609 entries, 0 to 21608
Data columns (total 21 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   ID                                         21609 non-null  int64
 1   Date House was Sold                        21609 non-null  object
 2   Sale Price                                 21609 non-null  float64
 3   No of Bedrooms                             21609 non-null  int64
 4   No of Bathrooms                            21609 non-null  float64
 5   Flat Area (in Sqft)                        21609 non-null  float64
 6   Lot Area (in Sqft)                         21609 non-null  float64
 7   No of Floors                               21609 non-null  float64
 8   Waterfront View                            21609 non-null  object
 9   No of Times Visited                        21609 non-null  object
 10  Condition of the House                     21609 non-null  object
 11  Overall Grade                              21609 non-null  int64
 12  Area of the House from Basement (in Sqft)  21609 non-null  float64
 13  Basement Area (in Sqft)                    21609 non-null  int64
 14  Age of House (in Years)                    21609 non-null  int64
 15  Renovated Year                             21609 non-null  int64
 16  Zipcode                                    21609 non-null  float64
 17  Latitude                                   21609 non-null  float64
 18  Longitude                                  21609 non-null  float64
 19  Living Area after Renovation (in Sqft)     21609 non-null  float64
 20  Lot Area after Renovation (in Sqft)        21609 non-null  int64
dtypes: float64(10), int64(7), object(4)
memory usage: 3.5+ MB

In [12]:
numerical_data=data.drop(columns=['ID','Date House was Sold','Sale Price','Waterfront View','No of Times Visited','Condition of the House','Overall Grade','Zipcode'])
numerical_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21609 entries, 0 to 21608
Data columns (total 13 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   No of Bedrooms                             21609 non-null  int64
 1   No of Bathrooms                            21609 non-null  float64
 2   Flat Area (in Sqft)                        21609 non-null  float64
 3   Lot Area (in Sqft)                         21609 non-null  float64
 4   No of Floors                               21609 non-null  float64
 5   Area of the House from Basement (in Sqft)  21609 non-null  float64
 6   Basement Area (in Sqft)                    21609 non-null  int64
 7   Age of House (in Years)                    21609 non-null  int64
 8   Renovated Year                             21609 non-null  int64
 9   Latitude                                   21609 non-null  float64
 10  Longitude                                  21609 non-null  float64
 11  Living Area after Renovation (in Sqft)     21609 non-null  float64
 12  Lot Area after Renovation (in Sqft)        21609 non-null  int64
dtypes: float64(8), int64(5)
memory usage: 2.1 MB

In [18]:
from sklearn.preprocessing import Normalizer
norm=Normalizer()
norm_data = norm.fit_transform(numerical_data)
norm_data =pd.DataFrame(norm_data,columns=numerical_data.columns)
norm_data.head()

   No of Bedrooms  ...  Lot Area after Renovation (in Sqft)
0        0.000363  ...                             0.682924
1        0.000264  ...                             0.672273
2        0.000152  ...                             0.611874
3        0.000527  ...                             0.658569
4        0.000263  ...                             0.656834

[5 rows x 13 columns]

In [19]:
tmp=norm_data.var()
tmp

No of Bedrooms                               4.071117e-08
No of Bathrooms                              2.802492e-08
Flat Area (in Sqft)                          1.231500e-02
Lot Area (in Sqft)                           1.351803e-02
No of Floors                                 3.008524e-08
Area of the House from Basement (in Sqft)    1.010140e-02
Basement Area (in Sqft)                      1.648493e-03
Age of House (in Years)                      2.002344e-05
Renovated Year                               1.684740e-03
Latitude                                     1.077875e-05
Longitude                                    7.109191e-05
Living Area after Renovation (in Sqft)       1.079222e-02
Lot Area after Renovation (in Sqft)          1.250016e-02
dtype: float64

In [20]:
T=1e-04
for i in tmp:
  if i < T:
    norm_data.drop(columns=[tmp[tmp==i].index[0]],inplace = True)
norm_data.var()

Flat Area (in Sqft)                          0.012315
Lot Area (in Sqft)                           0.013518
Area of the House from Basement (in Sqft)    0.010101
Basement Area (in Sqft)                      0.001648
Renovated Year                               0.001685
Living Area after Renovation (in Sqft)       0.010792
Lot Area after Renovation (in Sqft)          0.012500
dtype: float64